### ISSUE TITLE
question about lambda

### ISSUE THREAD

**Issue by markebrown** [christophercliff/flatmarket-server#3]
would the flatmarket server be able to run as an AWS lambda?
saw this function https://github.com/TaylorBriggs/stripe-lambda

**Comment by christophercliff** [comment]
I'm not an expert on Lambda, but I don't think it handles web requests like a Heroku would.

What I think you could do instead is port the [route handlers from hapi-flatmarket](https://github.com/christophercliff/hapi-flatmarket/blob/b9145e407926561f5ae092722961de675b173a89/lib/index.js#L47-L119) into lambda functions, then [configure them to be triggered by the AWS API Gateway](https://aws.amazon.com/about-aws/whats-new/2015/07/invoke-aws-lambda-functions-over-https/).

It's an interesting project, might have better performance/pricing than running flatmarket-server around the clock.

**Comment by christophercliff** [comment]
See https://github.com/christophercliff/flatmarket-service.
